#######################################################################################
# Book settings
title: Auto matadata generator for Depositar
author: dQuQb
logo: images/icons/logo.png

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : force

#######################################################################################
# HTML-specific settings
html:
  favicon                   : images/icons/favicon.png
  use_repository_button     : true
  use_issues_button         : true

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic
  binderhub_url             : "https://mybinder.org"
  colab_url                 : "https://colab.research.google.com"

repository:
  url                       : https://github.com/Mere-cat/Metadata-Generator-for-Depositar
  path_to_book              : docs/
  branch                    : main

